"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-15 21:33:22.721187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('membership', sa.String(length=30), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('preferred_colors', sa.JSON(), nullable=False),
    sa.Column('preferred_style', sa.String(length=100), nullable=False),
    sa.Column('recently_viewed_product_ids', sa.JSON(), nullable=False),
    sa.Column('liked_product_ids', sa.JSON(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('upcoming_schedule', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('line', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('CUSTOMER', 'STAFF')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('shopping_mode', sa.String(length=30), nullable=True),
    sa.Column('visit_purpose_code', sa.String(length=40), nullable=True),
    sa.Column('visit_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("shopping_mode IS NULL OR shopping_mode IN ('PRIVATE', 'STAFF_ASSISTED')", name='ck_checkins_shopping_mode'),
    sa.CheckConstraint("status IN ('CHECKED_IN', 'SELF_SHOPPING', 'WAITING_FOR_STAFF', 'ASSIGNED', 'SERVING', 'CANCELLED', 'COMPLETED')", name='ck_checkins_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_customer_id'), 'checkins', ['customer_id'], unique=False)
    op.create_index(op.f('ix_checkins_status'), 'checkins', ['status'], unique=False)
    op.create_index(op.f('ix_checkins_store_id'), 'checkins', ['store_id'], unique=False)
    op.create_table('customer_wishlist',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'product_id')
    )
    op.create_table('entry_tags',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("channel IN ('QR', 'NFC')", name='ck_entry_tags_channel'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_entry_tags_channel'), 'entry_tags', ['channel'], unique=False)
    op.create_index(op.f('ix_entry_tags_store_id'), 'entry_tags', ['store_id'], unique=False)
    op.create_table('inventories',
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventories_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'product_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('purchase_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('category_snapshot', sa.String(length=80), nullable=False),
    sa.Column('price_snapshot', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_history_customer_id'), 'purchase_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_purchase_history_product_id'), 'purchase_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_history_purchased_at'), 'purchase_history', ['purchased_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_store_id'), 'staff', ['store_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkin_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkin_id')
    )
    op.create_index(op.f('ix_consents_customer_id'), 'consents', ['customer_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkin_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('READY', 'FALLBACK', 'FAILED', 'REVOKED')", name='ck_recommendations_status'),
    sa.CheckConstraint("type IN ('LOOKBOOK', 'STAFF_GUIDE')", name='ck_recommendations_type'),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_checkin_id'), 'recommendations', ['checkin_id'], unique=False)
    op.create_index(op.f('ix_recommendations_customer_id'), 'recommendations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recommendations_input_hash'), 'recommendations', ['input_hash'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_type'), 'recommendations', ['type'], unique=False)
    op.create_table('staff_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkin_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_assignments_checkin_id'), 'staff_assignments', ['checkin_id'], unique=True)
    op.create_index(op.f('ix_staff_assignments_staff_id'), 'staff_assignments', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_assignments_staff_id'), table_name='staff_assignments')
    op.drop_index(op.f('ix_staff_assignments_checkin_id'), table_name='staff_assignments')
    op.drop_table('staff_assignments')
    op.drop_index(op.f('ix_recommendations_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_input_hash'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_customer_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_checkin_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_consents_customer_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_staff_store_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_purchase_history_purchased_at'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_product_id'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_customer_id'), table_name='purchase_history')
    op.drop_table('purchase_history')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_entry_tags_store_id'), table_name='entry_tags')
    op.drop_index(op.f('ix_entry_tags_channel'), table_name='entry_tags')
    op.drop_table('entry_tags')
    op.drop_table('customer_wishlist')
    op.drop_index(op.f('ix_checkins_store_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_status'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_customer_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('products')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
